import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  ContentType,
  OpcPackage,
  RelType,
  normaliseNamespaces,
  relsPathFor,
  relsSourcePart,
  resolveTarget,
} from '../src/opc.js';

const FIXTURES = new URL('../../../fixtures/generated/', import.meta.url);
const load = (name: string) => OpcPackage.read(new Uint8Array(readFileSync(new URL(name, FIXTURES))));

describe('path helpers', () => {
  it.each([
    ['_rels/.rels', ''],
    ['xl/_rels/workbook.xml.rels', 'xl/workbook.xml'],
    ['xl/worksheets/_rels/sheet1.xml.rels', 'xl/worksheets/sheet1.xml'],
  ])('relsSourcePart(%s) === %s', (rels, source) => {
    expect(relsSourcePart(rels)).toBe(source);
    expect(relsPathFor(source)).toBe(rels);
  });

  it.each([
    ['xl/workbook.xml', 'worksheets/sheet1.xml', 'xl/worksheets/sheet1.xml'],
    ['xl/workbook.xml', '/xl/styles.xml', 'xl/styles.xml'],
    ['xl/worksheets/sheet1.xml', '../drawings/drawing1.xml', 'xl/drawings/drawing1.xml'],
    ['', 'xl/workbook.xml', 'xl/workbook.xml'],
    ['xl/workbook.xml', './theme/theme1.xml', 'xl/theme/theme1.xml'],
  ])('resolveTarget(%s, %s) === %s', (source, target, want) => {
    expect(resolveTarget(source, target)).toBe(want);
  });
});

describe('strict conformance normalisation', () => {
  it('rewrites purl.oclc.org namespaces to the transitional ones', () => {
    const strict = '<worksheet xmlns="http://purl.oclc.org/ooxml/spreadsheetml/main"/>';
    expect(normaliseNamespaces(strict)).toBe(
      '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>',
    );
  });

  it('leaves transitional documents untouched', () => {
    const t = '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>';
    expect(normaliseNamespaces(t)).toBe(t);
  });
});

describe('reading real packages', () => {
  it('finds the main document and its flavour', () => {
    const pkg = load('features.xlsx');
    expect(pkg.mainDocumentPath()).toBe('xl/workbook.xml');
    expect(pkg.flavour()).toBe('xlsx');
    expect(pkg.hasMacros()).toBe(false);
  });

  it('resolves content types from Overrides and Defaults', () => {
    const pkg = load('features.xlsx');
    expect(pkg.contentType('xl/workbook.xml')).toBe(ContentType.xlsx);
    expect(pkg.contentType('xl/worksheets/sheet1.xml')).toBe(ContentType.worksheet);
    expect(pkg.contentType('_rels/.rels')).toBe(ContentType.relationships);
  });

  it('walks the workbook relationship table to every worksheet', () => {
    const pkg = load('features.xlsx');
    const sheets = pkg.related('xl/workbook.xml', RelType.worksheet);
    expect(sheets).toHaveLength(4);
    for (const s of sheets) expect(pkg.has(s.path)).toBe(true);
  });

  it('resolves a relationship id against the declaring part, not the workbook', () => {
    const pkg = load('features.xlsx');
    const rels = pkg.relationshipsOf('xl/workbook.xml');
    const first = rels.find((r) => r.type === RelType.worksheet)!;
    expect(pkg.resolve('xl/workbook.xml', first.id)).toMatch(/^xl\/worksheets\//);
  });

  it('retains every entry, including parts we do not model', () => {
    const pkg = load('features.xlsx');
    expect(pkg.has('xl/theme/theme1.xml')).toBe(true);
    expect(pkg.has('docProps/app.xml')).toBe(true);
    expect(pkg.has('[Content_Types].xml')).toBe(true);
  });

  it('rejects a package with no content types', () => {
    // A plain ODS is a zip but not an OPC package.
    expect(() => load('basic-types.ods')).toThrow(/Content_Types/);
  });
});

describe('round-tripping', () => {
  it('preserves every part byte-for-byte through open and save', () => {
    const original = new Uint8Array(readFileSync(new URL('features.xlsx', FIXTURES)));
    const pkg = OpcPackage.read(original);
    const saved = OpcPackage.read(pkg.write({ modified: new Date(0) }));

    for (const name of pkg.order) {
      if (name === '[Content_Types].xml') continue; // regenerated by design
      expect(Array.from(saved.bytes(name) ?? []), name).toEqual(Array.from(pkg.bytes(name)!));
    }
  });

  it('keeps the part set intact, which is the trust-critical property', () => {
    const pkg = load('features.xlsx');
    const saved = OpcPackage.read(pkg.write());
    expect([...saved.order].sort()).toEqual([...pkg.order].sort());
  });

  it('regenerates content types with the same mappings', () => {
    const pkg = load('features.xlsx');
    const saved = OpcPackage.read(pkg.write());
    for (const part of pkg.order) {
      expect(saved.contentType(part), part).toBe(pkg.contentType(part));
    }
  });

  it('is stable across repeated save cycles', () => {
    const pkg = load('styling.xlsx');
    const once = pkg.write({ modified: new Date(0) });
    const twice = OpcPackage.read(once).write({ modified: new Date(0) });
    expect(Array.from(twice)).toEqual(Array.from(once));
  });
});

describe('mutation', () => {
  it('drops calcChain, the one part we deliberately destroy', () => {
    const pkg = load('formulas.calc.xlsx');
    if (pkg.has('xl/calcChain.xml')) {
      pkg.dropCalcChain();
      expect(pkg.has('xl/calcChain.xml')).toBe(false);
      const saved = OpcPackage.read(pkg.write());
      expect(saved.has('xl/calcChain.xml')).toBe(false);
      // The relationship to it must go too, or Excel reports a broken package.
      const stale = saved
        .relationshipsOf('xl/workbook.xml')
        .filter((r) => r.target.includes('calcChain'));
      expect(stale).toHaveLength(0);
    }
  });

  it('mints relationship ids without colliding or renumbering existing ones', () => {
    const pkg = load('features.xlsx');
    const before = pkg.relationshipsOf('xl/workbook.xml').map((r) => r.id);
    const id = pkg.addRelationship('xl/workbook.xml', RelType.vbaProject, 'vbaProject.bin');
    expect(before).not.toContain(id);
    const after = pkg.relationshipsOf('xl/workbook.xml').map((r) => r.id);
    expect(after.slice(0, before.length)).toEqual(before);
  });

  it('adds a new part with its content type and survives a save', () => {
    const pkg = load('features.xlsx');
    pkg.putText('xl/custom.xml', '<custom/>', 'application/xml');
    const saved = OpcPackage.read(pkg.write());
    expect(saved.text('xl/custom.xml')).toBe('<custom/>');
  });

  it('refuses part names that escape the package', () => {
    const pkg = load('features.xlsx');
    expect(() => pkg.putText('../escape.xml', '<x/>')).toThrow(/escape/);
    expect(() => pkg.putText('/absolute.xml', '<x/>')).toThrow(/absolute/);
  });
});
